app:
    resource: '@AppBundle/Controller/'
    type: annotation

default:
    prefix: /
    resource: '@AppBundle/Resources/routing/default.yml'

schedule:
    prefix: /schedule
    resource: '@AppBundle/Resources/routing/schedule.yml'

agenda:
    prefix: /agenda
    resource: '@AppBundle/Resources/routing/agenda.yml'

task:
    prefix: /task
    resource: '@AppBundle/Resources/routing/task.yml'

profile:
    prefix: /profile
    resource: '@AppBundle/Resources/routing/profile.yml'

subject:
    prefix: /subject
    resource: '@AppBundle/Resources/routing/subject.yml'