default:
    path: /
    defaults: { _controller: app.controller.security:loginAction }

logout:
    path: /logout

login:
    path: /login
    defaults:
        _controller: app.controller.security:loginAction

register:
    path: /register
    defaults:
        _controller: app.controller.user:registerAction

register_through_invite:
    path: /register/invite/{hash}
    defaults:
        _controller: app.controller.user:registerThroughInviteAction

register_success:
    path: /register-success
    defaults:
        _controller: app.controller.user:registerSuccessAction

dashboard:
    path: /dashboard
    defaults: { _controller: app.controller.dashboard:indexAction }
