AppBundle\Entity\Subject:
    type: entity
    table: subject
    repositoryClass: AppBundle\Repository\SubjectRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            column: title
            type: string
            length: 60
        description:
            column: description
            type: string
            length: 255
            nullable: true

    oneToMany:
        tasks:
            targetEntity: AppBundle\Entity\Task
            mappedBy: subject
        grades:
            targetEntity: AppBundle\Entity\Grade
            mappedBy: subject
    manyToOne:
        profile:
            targetEntity: AppBundle\Entity\Profile
            inversedBy: subjects
            joinColumn:
                name: profile_id
                referenceColumnName: id
                onDelete: CASCADE

    lifecycleCallbacks: {  }