AppBundle\Entity\UserHasProfile:
    type: entity
    table: user_has_profile
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: AUTO
    fields:
        active:
            column: active
            type: boolean
        dateCreated:
            column: date_created
            type: datetime
            nullable: true
        profileInvite:
            column: profile_invite
            type: string
            nullable: true
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: userHasProfiles
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE
                cascade: ["persist"]
        profile:
            targetEntity: AppBundle\Entity\Profile
            inversedBy: profileHasUsers
            joinColumn:
                name: profile_id
                referencedColumnName: id
                onDelete: CASCADE
                cascade: ["persist"]

    lifecycleCallbacks: {  }