services:

  app.service.agenda:
      class: AppBundle\Service\AgendaService
      arguments:
          - '@doctrine.orm.entity_manager'

  app.service.filter:
      class: AppBundle\Service\FilterService
      arguments:
          - '@session'
          - '@request_stack'
