#services:
#
## Services
#
#
#    app.service.app:
#        class: AppBundle\Service\AppService
#        arguments:
#            - '@app.service.user'
#
#    app.service.base:
#        class: AppBundle\Service\BaseService
#        arguments:
#            - '@doctrine.orm.entity_manager'
#            - '@app.manager.mail'
#            - '@security.authorization_checker'
#
#    app.service.user:
#        class: AppBundle\Service\UserService
#        parent: app.service.base
